# Generated by Django 4.2.7 on 2023-12-13 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0002_alter_usuario_prestamo'),
    ]

    operations = [
        migrations.AddField(
            model_name='libro',
            name='valoracion_media',
            field=models.FloatField(default=0),
        ),
    ]
