# Generated by Django 4.2.7 on 2023-12-13 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0003_libro_valoracion_media'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libro',
            name='valoracion_media',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
