# Generated by Django 4.2.7 on 2023-12-14 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0005_libro_numero_valoraciones_alter_libro_disponibilidad_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='prestamo',
            name='valoracion_usuario',
            field=models.IntegerField(default=None),
        ),
    ]
