# Generated by Django 4.2.7 on 2023-12-14 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0009_alter_prestamo_valoracion_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='prestamo',
            name='numero_valoraciones',
            field=models.IntegerField(default=0),
        ),
    ]
