# Generated by Django 4.2.7 on 2023-12-14 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0010_prestamo_numero_valoraciones'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='prestamo',
            new_name='prestamo_actual',
        ),
    ]
