# Generated by Django 4.2.7 on 2023-12-14 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0011_rename_prestamo_usuario_prestamo_actual'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prestamo',
            name='valoracion_usuario',
            field=models.IntegerField(default=None),
        ),
    ]
