# Generated by Django 4.2.7 on 2023-12-14 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0013_alter_libro_numero_valoraciones'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libro',
            name='numero_valoraciones',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='prestamo',
            name='numero_valoraciones',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='prestamo',
            name='valoracion_usuario',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
    ]
