# Generated by Django 4.2.7 on 2023-12-15 12:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0014_alter_libro_numero_valoraciones_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Valoraciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valoracion', models.FloatField()),
                ('prestamo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='biblioteca.prestamo')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
