# Generated by Django 4.2.7 on 2023-12-16 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0015_valoracion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='valoracion',
            name='libro',
        ),
    ]
