# Generated by Django 4.2.7 on 2023-12-16 10:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0016_remove_valoracion_libro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='valoracion',
            name='prestamo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='biblioteca.prestamo'),
        ),
        migrations.AlterField(
            model_name='valoracion',
            name='valoracion',
            field=models.IntegerField(default=0),
        ),
    ]
