# Generated by Django 4.2.7 on 2023-12-16 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0017_alter_valoracion_prestamo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='libro',
            name='numero_valoraciones',
        ),
        migrations.RemoveField(
            model_name='libro',
            name='valoracion_media',
        ),
    ]
