# Generated by Django 4.2.7 on 2023-12-16 20:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0019_libro_valoracion_media'),
    ]

    operations = [
        migrations.AddField(
            model_name='libro',
            name='numero_valoraciones',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='valoracion',
            name='prestamo',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='biblioteca.prestamo'),
        ),
        migrations.AlterField(
            model_name='valoracion',
            name='usuario',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='valoracion',
            name='valoracion',
            field=models.FloatField(),
        ),
    ]
