# Generated by Django 4.2.7 on 2023-12-16 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0020_libro_numero_valoraciones_alter_valoracion_prestamo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='valoracion',
            name='valoracion',
        ),
        migrations.AddField(
            model_name='valoracion',
            name='rating',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
    ]
