# Generated by Django 4.2.7 on 2023-12-17 14:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0022_rename_prestamo_valoracion_prestamo_valoracion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='valoracion',
            name='usuario_valoracion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
