# Generated by Django 4.2.7 on 2023-12-18 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0023_alter_valoracion_usuario_valoracion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='libro',
            name='numero_valoraciones',
        ),
    ]
